name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  REGION: us-central1
  BACKEND_SERVICE_NAME: pfm-backend-pr-${{ github.event.pull_request.number }}
  FRONTEND_SERVICE_NAME: pfm-frontend-pr-${{ github.event.pull_request.number }}

jobs:
  cleanup:
    name: Clean up PR resources
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Delete Backend Service
        run: |
          gcloud run services delete ${{ env.BACKEND_SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --quiet || echo "Backend service not found"

      - name: Delete Frontend Service
        run: |
          gcloud run services delete ${{ env.FRONTEND_SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --quiet || echo "Frontend service not found"

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `## 🧹 Preview Deployment Cleaned Up
            
            The preview deployment for this PR has been removed.
            
            Thank you for your contribution!`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });